services:
  opensearch:
    image: opensearchproject/opensearch:3.3.0
    container_name: opensearch-node1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms16384m -Xmx16384m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Developer@123
      - OPENSEARCH_HOME=/usr/share/opensearch
      - "node.roles: [ ml ]"
      - "plugins.ml_commons.model_access_control_enabled=true"
      - "plugins.ml_commons.only_run_on_ml_node=false"
      - "plugins.ml_commons.native_memory_threshold=99"
      - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/lib:/usr/local/lib64:/usr/lib64:/usr/share/opensearch/plugins/opensearch-knn/lib
      - path.repo=/usr/share/opensearch/snapshots
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ../0. DATA/snapshots:/usr/share/opensearch/snapshots
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.3.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    networks:
      - opensearch-net

  ollama:
    container_name: ollama
    image: ollama/ollama:0.14.1
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    pull_policy: always
    tty: true
    entrypoint: ["/bin/bash", "/ollama-entrypoint.sh"]
    networks:
      - opensearch-net

volumes:
  opensearch-data:
  opensearch-snapshots:
  ollama_data:

networks:
  opensearch-net:
