services:
  opensearch-node1:
    image: opensearchproject/opensearch:3.3.0
    container_name: opensearch-optimized-node1
    environment:
      - cluster.name=opensearch-optimized-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_HOME=/usr/share/opensearch
      # Optimized JVM settings (50% of 16GB = 8GB)
      - "OPENSEARCH_JAVA_OPTS=-Xms8g -Xmx8g"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD:-Developer@123}
      # Cluster-level optimizations
      - "cluster.routing.allocation.balance.prefer_primary=true"
      - "segrep.pressure.enabled=true"
      - "plugins.ml_commons.only_run_on_ml_node=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - opensearch-optimized-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  opensearch-node2:
    image: opensearchproject/opensearch:3.3.0
    container_name: opensearch-optimized-node2
    environment:
      - cluster.name=opensearch-optimized-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_HOME=/usr/share/opensearch
      - "plugins.ml_commons.only_run_on_ml_node=false"
      - "OPENSEARCH_JAVA_OPTS=-Xms8g -Xmx8g"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD:-Developer@123}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-optimized-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.3.0
    container_name: opensearch-optimized-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch-node1:9200","https://opensearch-node2:9200"]
    networks:
      - opensearch-net

volumes:
  opensearch-optimized-data1:
  opensearch-optimized-data2:

networks:
  opensearch-net: